version: '3.8'

services:
  verdict-ai-backend:
    build: .
    ports:
      - "8000:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
      - PORT=8080
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - verdict-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx-docker.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - verdict-ai-backend
    restart: unless-stopped
    networks:
      - verdict-network

networks:
  verdict-network:
    driver: bridge
